# Generated by Django 3.0 on 2020-04-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ม.1', 'ม.1'), ('ม.2', 'ม.2'), ('ม.3', 'ม.3'), ('ม.4', 'ม.4'), ('ม.5', 'ม.5'), ('ม.6', 'ม.6')], default='ม.1', max_length=100)),
                ('document_name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='alldocument')),
                ('other', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
